repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, "--line-length=140"]
      - id: ruff-format
        args: ["--line-length=140"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
      - id: check-added-large-files
        args: [ "--maxkb=600" ]

  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [ commit ]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
