# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/python-poetry/poetry
    rev: 1.4.2 # should be the same as the version of poetry used in the CI
    hooks:
      - {id: poetry-check, args: [-C, ./src]}
      - {id: poetry-lock, args: [--no-update, -C, ./src]}
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
        # pre-commit run --all-files forces all files to be processed; except when explicitly force excluded
      - id: ruff
        args: [ --config, src/pyproject.toml, --fix, --exit-non-zero-on-fix, --extend-exclude, "docs,notebooks"]
        always_run: true
      - id: ruff-format
        args: [--check, --config, src/pyproject.toml,]
        language: python
        require_serial: true
        types_or: [ python, jupyter ]
        additional_dependencies: [ ".[jupyter]" ]
        always_run: true
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
  - repo: local
    hooks:
      - id: mypy
        exclude: 'notebooks'
        name: mypy
        entry: mypy
        language: system
        types: [python]
        require_serial: true
        args: [--config-file=mypy.ini]
        files: '^src/'
